<a href="https://colab.research.google.com/github/kanishka55/hj/blob/main/f1score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
import re

In [4]:
df = pd.read_csv('/content/drive/MyDrive/colab/OS/Datasets/labeled_data.csv')

In [5]:
df

Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]

In [6]:
df.shape

(24783, 7)

In [7]:
df['tweet']

0        !!! RT @mayasolovely: As a woman you shouldn't...
1        !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2        !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3        !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4        !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...
                               ...                        
24778    you's a muthaf***in lie &#8220;@LifeAsKing: @2...
24779    you've gone and broke the wrong heart baby, an...
24780    young buck wanna eat!!.. dat nigguh like I ain...
24781                youu got wild bitches tellin you lies
24782    ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...
Name: tweet, Length: 24783, dtype: object

In [8]:
import numpy as np
import pandas as pd
from tqdm import tqdm

import re
import string

import nltk
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer  
stop_words = stopwords.words('english')


from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report

import matplotlib.pyplot as plt
import seaborn as sns

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
sw = stopwords.words('english')
new_stopwords = ["rt","shouldnt","ya","yous","youve","youu"]
sw.extend(new_stopwords)
lemmatizer = WordNetLemmatizer() 

def clean_text(text):
    
    text = text.lower()
    
    text = re.sub(r"[^a-zA-Z?.!,¿]+", " ", text) # replacing everything with space except (a-z, A-Z, ".", "?", "!", ",")

    
    punctuations = '@#!?+&*[]-%.:/();$=><|{}^' + "'`" + '_'
    for p in punctuations:
        text = text.replace(p,'') #Removing punctuations
        
    text = [word.lower() for word in text.split() if word.lower() not in sw]
    
    text = [lemmatizer.lemmatize(word) for word in text]
    
    text = " ".join(text) #removing stopwords
    return text

In [10]:
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [11]:
df['text'] = df['tweet'].apply(lambda x: clean_text(x))
 
df['text']

0        mayasolovely woman complain cleaning house amp...
1        mleew boy dat coldtyga dwn bad cuffin dat hoe ...
2        urkindofbrand dawg sbaby life ever fuck bitch ...
3                 c g anderson viva based look like tranny
4        shenikaroberts shit hear might true might fake...
                               ...                        
24778    muthaf lie lifeasking pearl corey emanuel righ...
24779     gone broke wrong heart baby, drove redneck crazy
24780    young buck wanna eat dat nigguh like aint fuck...
24781                            got wild bitch tellin lie
24782    ruffled ntac eileen dahlia beautiful color com...
Name: text, Length: 24783, dtype: object

In [12]:
sample_corpora = df['text']
sample_corpora

0        mayasolovely woman complain cleaning house amp...
1        mleew boy dat coldtyga dwn bad cuffin dat hoe ...
2        urkindofbrand dawg sbaby life ever fuck bitch ...
3                 c g anderson viva based look like tranny
4        shenikaroberts shit hear might true might fake...
                               ...                        
24778    muthaf lie lifeasking pearl corey emanuel righ...
24779     gone broke wrong heart baby, drove redneck crazy
24780    young buck wanna eat dat nigguh like aint fuck...
24781                            got wild bitch tellin lie
24782    ruffled ntac eileen dahlia beautiful color com...
Name: text, Length: 24783, dtype: object

In [13]:
count_vectorizer = CountVectorizer(min_df=0.3, max_df=0.7)
wm = count_vectorizer.fit_transform(sample_corpora).toarray()
wm

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [0]])

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,classification_report

import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
from tkinter import YView
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfconverter = TfidfVectorizer(min_df=0.3, max_df=0.7)
Y = tfidfconverter.fit_transform(sample_corpora).toarray()

In [16]:
Y

array([[0.],
       [0.],
       [1.],
       ...,
       [0.],
       [1.],
       [0.]])

In [17]:
from sklearn.cluster import KMeans
import numpy as np

In [18]:
km=KMeans(n_clusters=2,n_init=25,random_state=23)
km.fit(Y)
y_cluster=km.predict(wm)
y_cluster

array([1, 1, 0, ..., 1, 0, 1], dtype=int32)

In [19]:
#Count Cluster
from collections import Counter
cnt=Counter(y_cluster)
cnt

Counter({1: 14147, 0: 10636})

In [30]:
y=y
X=df.drop(y, axis=1)
print ("X dataset shape : ",X.shape)
print ("y dataset shape : ",y.shape)

KeyError: ignored

In [26]:
from sklearn.svm import SVC
model_2 = SVC()

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)
print ("Train size : ",X_train.shape)
print ("Test size : ",X_test.shape)

Train size :  (19826, 7)
Test size :  (4957, 7)


In [28]:

from sklearn.metrics import f1_score

In [29]:
model_2.fit(X_train,y_train)

ValueError: ignored

In [ ]:
f1_score(y_train, y_test, average='weighted')

ValueError: ignored